"""Add treatment, priority, weight to appointments

Revision ID: 50409e86bbbb
Revises: 4f6425d2748c
Create Date: 2025-05-05 19:46:41.765095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '50409e86bbbb'
down_revision: Union[str, None] = '4f6425d2748c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add treatment, priority, weight to appointments if they don't exist."""

    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("appointments")]

    if "treatment" not in columns:
        op.add_column(
            "appointments",
            sa.Column("treatment", sa.String(length=255), nullable=True),
        )

    if "priority" not in columns:
        op.add_column(
            "appointments",
            sa.Column("priority", sa.Integer(), nullable=True),
        )

    if "weight" not in columns:
        op.add_column(
            "appointments",
            sa.Column("weight", sa.Float(), nullable=True),
        )




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.create_foreign_key(None, 'medical_records', 'animals', ['animal_id'], ['id'])
    op.add_column('appointments', sa.Column('status', sa.VARCHAR(), nullable=False))
    op.drop_column('appointments', 'weight')
    op.drop_column('appointments', 'priority')
    op.drop_column('appointments', 'treatment')
    # ### end Alembic commands ###
